server:
  port: ${port:8006}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: provider-log
  data:
    mongodb:
      host: 127.0.0.1
      database: logDb
      port: 27017
